# Generated by Django 2.2.2 on 2019-06-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190618_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postHit',
            field=models.IntegerField(default=0),
        ),
    ]
